### ISSUE TITLE
First test of software

### ISSUE THREAD

**Issue by jfhawkin** [TomasdelaBarra/QTRANUS#12]
**Attempting to use our Toronto model/network**
1.	Shapefiles load well
2.	TRANUS working directory loads and populates base scenario in left window. Scenario appears, but no data appears. Gives message ‘database connection unsatisfactory’. 
3.	Data window not bringing up the data for our model. Clicking ‘help’ brings up a help page for ‘Network’ rather than ‘Data’. ‘Data’ appears in the help structure, but there is no page connected to it.
4.	Clicking on ‘Add Scenario’ button gives:
```
An error has occurred while executing Python code: 
TypeError: object of type 'bool' has no len() 
Traceback (most recent call last):
  File "C:/Users/jason/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QTRANUS\scenarios_dialog.py", line 108, in open_add_scenario_window
    dialog = AddScenarioDialog(self.tranus_folder,  parent = self)
  File "C:/Users/jason/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QTRANUS\add_scenario_dialog.py", line 45, in __init__
    self.__load_scenarios_combobox()
  File "C:/Users/jason/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QTRANUS\add_scenario_dialog.py", line 122, in __load_scenarios_combobox
    if len(scenarios) > 0:
TypeError: object of type 'bool' has no len()
```
It appears 'scenarios' is a bool object and not an integer as expected.

**Following 2019 QTRANUS document with Swindon example.**
I tried the same procedure with the Swindon model and it seems to work. However, clicking ‘save’ for this model gives the error:
An error has occurred while executing Python code: 
AttributeError: module 'PyQt5.QtGui' has no attribute 'QMessageBox' 
```
Traceback (most recent call last):
  File "C:/Users/jason/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QTRANUS\classes\data\DataBaseDataAccess.py", line 77, in save_db
    stringList = (newDbFileName.replace('/', '\\')).split('\\')
AttributeError: 'NoneType' object has no attribute 'replace'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/jason/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QTRANUS\data_dialog.py", line 158, in save_db
    if(self.dataBase.save_db(self.project['tranus_folder'], self.project.db_path, self.project.db_path, DBFiles.Scenarios, self.scenariosMatrix)):
  File "C:/Users/jason/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QTRANUS\classes\data\DataBase.py", line 32, in save_db
    return self.database_data_access.save_db(path, dbFileName, newDbFileName, dbFile, matrix)
  File "C:/Users/jason/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QTRANUS\classes\data\DataBaseDataAccess.py", line 109, in save_db
    messagebox = QTranusMessageBox.set_new_message_box(QtGui.QMessageBox.Warning, "Save DB", "Unexpected error: {0}".format(sys.exc_info()[0]), ":/plugins/QTranus/icon.png", None, buttons = QtGui.QMessageBox.Ok)
AttributeError: module 'PyQt5.QtGui' has no attribute 'QMessageBox'
```
Is the 'data' window currently operational? I can have a look at other components outlined in the tutorials, but would need the shapefiles (could generate them myself, but would be easier to use same files so I can check operability using same inputs).

**Comment by yanezlb** [comment]
Fixed
